name: qbittorrent-vpn
description: The qBittorrent project aims to provide an open-source software alternative
  to µTorrent and VPN functionalities have been added to this application.
annotations:
  title: qBittorrent with vpn
  type: application
  version: 1.2.12
  apiVersion: v2
  appVersion: 4.6.5
  kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.9
home: https://www.qbittorrent.org/
icon: https://media.sys.truenas.net/apps/qbittorrent/icons/icon.png
sources:
  - https://github.com/onedr0p/containers/tree/main/apps/qbittorrent
  - https://github.com/truenas/charts/tree/master/community/qbittorrent-vpn
  - https://www.qbittorrent.org/
  - https://hub.docker.com/r/mjmeli/qbittorrent-port-forward-gluetun-server
keywords:
  - media
  - torrent
  - download
